ARG BASE_IMAGE=droste-tome
FROM ${BASE_IMAGE}

LABEL description="droste-press: C/C++ development toolchain (loom equivalent)"

USER root

RUN apt-get -qq update \
    && apt-get -qq install -y --no-install-recommends \
      build-essential cmake pkg-config \
      autoconf automake libtool \
      gdb valgrind \
      ccache ninja-build bear \
    && rm -rf /var/lib/apt/lists/*

USER droste
