ARG BASE_IMAGE=droste-tome
FROM ${BASE_IMAGE}

LABEL description="droste-tome-lxc: bootable tome (kento system container)"

USER root

COPY oci/seed-oci-exclude.txt /tmp/seed-oci-exclude.txt
RUN apt-get -qq update \
    && apt-get -qq install -y --no-install-recommends \
       $(grep -v '^#' /tmp/seed-oci-exclude.txt | grep -v '^$') \
       ipvsadm molly-guard cifs-utils nfs-common fatrace lxcfs \
       lvm2 thin-provisioning-tools nbd-client quota pciutils hdparm \
       dmidecode bridge-utils \
       drbd-utils sbd dlm-controld open-iscsi targetcli-fb multipath-tools \
       sg3-utils smartmontools apparmor-utils qemu-system-arm \
    && rm -f /tmp/seed-oci-exclude.txt \
    && rm -rf /var/lib/apt/lists/*

CMD ["/sbin/init"]
